runtime: custom
env: flex
service: culinary-frontend-service


instance_class: F1

env_variables:
  DISABLE_METRICS_COLLECTION: "true"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
