runtime: custom
env: flex
service: culinary-frontend-service

endpoints_api_service:
  name: culinary-frontend-service-dot-culinary-portal.lm.r.appspot.com
  rollout_strategy: managed

instance_class: F1

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
